runtime: python311
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: "ubuntu22"

api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

